[meta]
name     = "Better TOTD"
author   = "XertroV"
category = "Race"
version  = "0.1.10"
siteid   = 352

[script]
#__DEFINES__
dependencies = ["NadeoServices"]
optional_dependencies = ["Archivist", "ManiaExchange", "MLHook"]
# exports = ["Exports_BetterTotd.as"]
#defines = ["UNIT_TEST"]
